# .streamlit/secrets.toml
SUPABASE_URL = "https://xjvpcpvdyddfstbkkmaq.supabase.co"  # Substitua pela sua URL
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqdnBjcHZkeWRkZnN0YmtrbWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNjQ4MzgsImV4cCI6MjA2MTY0MDgzOH0.rtD9LKTFUG0P7I7lMtxWy1UviL3E6GBuo1_V06j4m_g"  # Substitua pela sua chave
